#!/bin/bash

source ./text_fn

TOTAL_LOAD=$( awk -v cpus=$(nproc) '{printf "%.0f%% (1 min) | %.0f%% (5 min) | %.0f%% (15 min)\n", ($1*100)/cpus, ($2*100)/cpus, ($3*100)/cpus}' /proc/loadavg)
CPUTIME=$(ps -eo pcpu | awk 'NR>1' | awk '{tot=tot+$1} END {print tot}')
CPUCORES=$(nproc)
UP=$(echo `uptime` | awk '{ print $3 " " $4 }')
DATE=$(date)

echo "
--------------------------------------------------------------------------------
`center_text "SYSTEM STATUS"`
`center_text "($DATE)"`
--------------------------------------------------------------------------------

`section_title 💻 "Server Information"`

`section_title 📊 "Performance Metrics"`
--------------------------------------------------------------------------------
   - Uptime             : $UP
   - Load Averages      : $TOTAL_LOAD
   - CPU Usage (average): `echo $CPUTIME / $CPUCORES | bc`%

`section_title 🧠 "Memory Stats"`

`section_title 💾 "Disk Information"`

"
